### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [rsms/immutable-cpp#2]
I was wondering how difficult or possible it would be to have an immutable persistant hashmap in c++ ? Thanks

**Comment by rsms** [comment]
It wouldn't be that hard, assuming the implementation would use a trie like the array collection type. One way of implementing a map is to hash the keys, use the trie implementation underpinning Array, removing the bounds restriction (some functions rely on verified bounds, so a few things would need to be changed to no longer assume limited bounds.) Then just take the hash value and use that as the index. It's pretty straight-forward actually.
